- hosts: master
  become: yes
  tasks:
    - name: Get kubeadm join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: Set join command as a fact
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"


- hosts: workers
  become: yes
  tasks:
    - name: Ensure master node (6443) is reachable from workers
      wait_for:
        host: "{{ hostvars[groups['master'][0]]['ansible_default_ipv4']['address'] }}"
        port: 6443
        timeout: 10
        state: started
      retries: 5
      delay: 3

    - name: Join worker nodes to the Kubernetes cluster
      shell: "{{ hostvars[groups['master'][0]].join_command }} >> node_joined.log"
      args:
        chdir: /home/ubuntu
        creates: node_joined.log
